define [
		'apps/content-preview/content-board/elements/hotspot/controller'
		'apps/content-preview/content-board/elements/row/controller'
		'apps/content-preview/content-board/elements/text/controller'
		'apps/content-preview/content-board/elements/image/controller'
		'apps/content-preview/content-board/elements/imagewithtext/controller'
		'apps/content-preview/content-board/elements/mcq/controller'
		'apps/content-preview/content-board/elements/fib/controller'
		# 'apps/content-creator/content-builder/elements/biganswer/controller'
		'apps/content-preview/content-board/elements/sort/controller'
		'apps/content-preview/content-board/elements/teacherquestion/controller'
		'apps/content-preview/content-board/elements/video/controller'
        'apps/content-preview/content-board/elements/audio/controller'
        'apps/content-preview/content-board/elements/table/controller'
		],->