// Generated by CoffeeScript 1.7.1
(function() {
  define(['apps/content-preview/content-board/elements/row/controller', 'apps/content-preview/content-board/elements/text/controller', 'apps/content-preview/content-board/elements/mcq/controller', 'apps/content-preview/content-board/elements/fib/controller', 'apps/content-preview/content-board/elements/sort/controller'], function() {});

}).call(this);
