define [
			'underscore'
			'jquery'
			'jqueryui'
			'jqueryresize'
			'underscorestring'
			'kinetic'
			'plupload'
			'kineticresize'
			'backbone'
			'marionette'
			'mustache'
			'syphon'
			'text'
			'jqueryvalidate'
			'bootstrap'
			'checkbox'
			'bootstrapslider'
			'spin'
			'jqueryspin'
			'jquerycolor'
		], ->