define [
			'underscore'
			'jquery'
			'jqueryui'
			'bridget'
			'isotope'
			'jqueryresize'
			'underscorestring'
			'kinetic'
			'plupload'
			'kineticresize'
			'backbone'
			'marionette'
			'mustache'
			'syphon'
			'text'
			'jqueryvalidate'
			'bootstrap'
			'checkbox'
			# 'bootstrapslider'
			'spin'
			'jqueryspin'
			# 'jquerycolor'
			# 'jqueryknob'
			# 'select2'
			# 'tagsinput'
			'screwbuttons'
			'videojs'
		], ->