define [
			'underscore'
			'underscorestring'
			'jquery'
			'backbone'
			'marionette'
			'syphon'
			'text'
			'jqueryvalidate'
			'sidr'
			'slimroll'
			'core'
			'breakpoints'
			'mustache'
			'spin'
			'jqueryspin'
			'bootstrap'
			'mixitup'
			#'jquery_datatables'
			#'tabletools'
			#'datatables_responsive'
			#'datatables'
			'unveil'
		], ->