define [
	# 'entities/base-entities'
	'entities/user'
	'entities/menu'
	'entities/textbooks'
	'entities/chapters'
	# 'entities/schools'
	# 'entities/breadcrumb'
	'entities/content-group'
	'entities/divisions'
	'entities/quiz'
	'entities/quiz-question-response'
	'entities/quiz-response-summary'
	'entities/content-pieces'
	# 'entities/question-response'
	# 'entities/content-creator/element'
	# 'entities/content-creator/media'
	# 'entities/content-creator/hotspotelement'
	# 'entities/content-creator/questionelement'
	# 'entities/content-creator/option'
	# 'entities/content-creator/json'
	# 'entities/answer'
	# 'entities/grading-parameter'
	# 'entities/communications'
], ->
