// Generated by CoffeeScript 1.7.1
jQuery(document).ready(function($) {
  console.log(ajaxurl);
  $('.image-upload').fileupload({
    url: ajaxurl + '?request="fileupload"',
    dataType: 'json',
    done: function(e, data) {
      var progress;
      $(this).closest('.row').find(".attachment_id").val(data.result.attachment_id);
      $(this).closest('.row').find(".attachment_url").val(data.result.attachment_url);
      $(this).closest('.row').find('.success_container').html('');
      if ((data.files[0].type === 'image/jpeg') || (data.files[0].type === 'image/png') || (data.files[0].type === 'image/gif')) {
        $(this).closest('.row').find('.success_container').append('<span><img id="attachment-id-' + data.result.attachment_id + '" src="' + data.result.attachment_url + '" width="150" height="100"   style="height:100px;"/>');
      } else {
        $(this).closest('.row').find('.success_container').append('<span>Invalid Image Type</span>');
      }
      progress = parseInt(data.loaded / data.total * 100, 10);
      $(this).closest('.row').find('.progress .bar').css('width', progress + '%');
      $(this).closest('.row').find('.progress').fadeOut('slow');
      return $(this).removeAttr("disabled");
    },
    start: function(e, data) {
      var progress;
      $(this).attr("disabled", "disabled");
      $(this).closest('.row').find('.progress').show();
      progress = parseInt(data.loaded / data.total * 100, 10);
      return $(this).closest('.row').find('.progress .bar').css('width', progress + '%');
    }
  });
  if ($('.date-field').length > 0) {
    $('.date-field').datepicker({
      dateFormat: 'dd-mm-yy'
    });
  }
  return $('#parent').change(function() {
    if ($('#parent').val() === '-1') {
      return $('.textbook_fields').show();
    } else {
      return $('.textbook_fields').hide();
    }
  });
});
