define ['cordova/entities/app-menu'
		'cordova/entities/app-user'
		'cordova/entities/app-textbooks'
		'cordova/entities/app-divisions'
		'cordova/entities/app-chapters'
		'cordova/entities/app-content-group'
		'cordova/entities/app-quiz'
		'cordova/entities/app-quiz-response-summary'
		'cordova/entities/app-quiz-question-response'
		'cordova/entities/app-content-piece'
		'cordova/entities/app-media'
		], ->