define ['apps/content-creator/content-builder/elements/hotspot/controller'
		'apps/content-creator/content-builder/elements/row/controller'
		'apps/content-creator/content-builder/elements/text/controller'
		'apps/content-creator/content-builder/elements/image/controller'
		'apps/content-creator/content-builder/elements/imagewithtext/controller'
		'apps/content-creator/content-builder/elements/mcq/controller'
		'apps/content-creator/content-builder/elements/fib/controller'
		'apps/content-creator/content-builder/elements/biganswer/controller'
		'apps/content-creator/content-builder/elements/sort/controller'
		'apps/content-creator/content-builder/elements/teacherquestion/controller'
		'apps/content-creator/content-builder/elements/video/controller'
        'apps/content-creator/content-builder/elements/audio/controller'
        'apps/content-creator/content-builder/elements/table/controller'
],->