define [
		# 'apps/content-board/elements/hotspot/controller'
		'apps/content-board/elements/row/controller'
		'apps/content-board/elements/text/controller'
		'apps/content-board/elements/image/controller'
		'apps/content-board/elements/imagewithtext/controller'
		# 'apps/content-board/elements/mcq/controller'
		# 'apps/content-board/elements/fib/controller'
		# 'apps/content-board/elements/biganswer/controller'
		# 'apps/content-board/elements/sort/controller'
		'apps/content-board/elements/teacherquestion/controller'
		'apps/content-board/elements/video/controller'
        'apps/content-board/elements/audio/controller'
        'apps/content-board/elements/table/controller'
		],->