define [
    'apps/login/loginapp'
    'apps/header/headerapp'
    'apps/left-nav/leftnavapp'
    # 'apps/textbooks/app'
    #'apps/breadcrumb/app'
    'apps/content-modules/content-modules-app'
    'apps/students-dashboard/teachers-dashboard-app' 
    'apps/quiz-modules/quiz-module-app' 
    'apps/teaching-modules/textbook-modules-controller'
    # 'apps/take-module-item/take-module-item-app'
    # 'apps/content-preview/controller'
    # 'apps/content-pieces/content-pieces-app'
    # 'apps/admin-content-modules/app'
    # 'apps/popup-dialog/single-edit-popup/single-edit-popup-controller'
    # 'apps/app-sync/app'
], ->