// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app'], function(App) {
    return App.module('ContentPreview.ContentBoard.Element.Text.Views', function(Views, App, Backbone, Marionette, $, _) {
      return Views.TextView = (function(_super) {
        __extends(TextView, _super);

        function TextView() {
          return TextView.__super__.constructor.apply(this, arguments);
        }

        TextView.prototype.tagName = 'p';

        TextView.prototype.template = '';

        TextView.prototype.className = 'text';

        TextView.prototype.onShow = function() {
          return this.$el.append(_.stripslashes(this.model.get('content')));
        };

        return TextView;

      })(Marionette.ItemView);
    });
  });

}).call(this);
