({
  baseUrl: './js',
  name: 'plugins/almond',
  include : 'walnut-main',
  optimize: 'none',
  wrap: false,
  out: '../production/walnut-main.js',
  paths: {
    jquery: 'plugins/jquery',
    jqueryui: 'plugins/jquery.ui',
    bootstrap     : 'plugins/bootstrap',
    jqueryvalidate: 'plugins/jquery.validate.min',
    underscore: 'plugins/underscore',
    backbone: 'plugins/backbone',
    marionette: 'plugins/backbone.marionette',
    text: 'plugins/text',
    app: 'walnut-app',
    syphon: 'plugins/backbone.syphon',
    sidr: 'plugins/jquery.sidr.min',
    slimroll: 'plugins/jquery.slimscroll.min',
    breakpoints: 'plugins/breakpoints',
    mustache: 'plugins/mustache',
    core: 'plugins/core',
    mixitup       : 'plugins/jquery.mixitup.min',
    search_results    : 'plugins/search_results',
    spin        : 'plugins/spin',
    jqueryspin      : 'plugins/jquery.spin',
    componentloader   : 'components/component-loader',
   // jquery_datatables     : 'plugins/jquery.dataTables.min',
    //tabletools      : 'plugins/TableTools.min',
    //datatables_responsive: 'plugins/datatables.responsive',
    //datatables      : 'plugins/datatables',
    unveil        : 'plugins/jquery.unveil.min',
    pace        : 'plugins/pace'
  },
  shim: {
    underscore: {
      exports: '_'
    },
    jquery: ['underscore'],
    jqueryui: ['jquery'],
    bootstrap: ['jquery'],
    backbone: {
      deps: ['jquery', 'underscore'],
      exports: 'Backbone'
    },
    marionette: {
      deps: ['backbone'],
      exports: 'Marionette'
    },
    sidr: ['jquery'],
    unveil: ['jquery'],
    slimroll: ['jquery'],
    core: ['sidr', 'jquery'],
    breakpoints: ['jquery'],
    jqueryvalidate: ['jquery'],
    syphon: ['backbone'],
    mixitup     : ['jquery'],
    search_results    : ['jquery','mixitup'],
   // jquery_datatables     : ['jquery'],
   // tabletools    : ['jquery_datatables'],
   // datatables_responsive     : ['jquery_datatables'],
   // datatables    : ['jquery_datatables','bootstrap'],
    app: ['plugins/walnut-pluginloader', 'config/walnut-configloader'],
  }
})