({
	baseUrl: './js',
	name: 'plugins/almond',
	include: 'cordova-students-main',
	// optimize: 'none',
	wrap: false,
	out: '../production/cordova-students-main.js',
	paths: {
		jquery: 'plugins/jquery',
		jqueryui: 'plugins/jquery.ui',
		bootstrap: 'plugins/bootstrap.min',
		jqueryvalidate: 'plugins/jquery.validate.min',
		underscore: 'plugins/underscore',
		underscorestring: 'plugins/underscorestring',
		backbone: 'plugins/backbone',
		marionette: 'plugins/backbone.marionette',
		text: 'plugins/text',
		app: 'walnut-app',
		syphon: 'plugins/backbone.syphon',
		sidr: 'plugins/jquery.sidr.min',
		slimroll: 'plugins/jquery.slimscroll.min',
		breakpoints: 'plugins/breakpoints',
		mustache: 'plugins/mustache',
		core: 'plugins/core',
		mixitup: 'plugins/jquery.mixitup.min',
		spin: 'plugins/spin',
		jqueryspin: 'plugins/jquery.spin',
		componentloader: 'components/component-loader',
		unveil: 'plugins/jquery.unveil.min',
		detect: 'plugins/detect',
		tablesorter: 'plugins/jquery.tablesorter',
		tablesorter_pager: 'plugins/jquery.tablesorter.pager',
		moment: 'plugins/moment.min',
		detect: 'plugins/detect',
		kinetic             : 'plugins/kinetic',
		kineticresize       : 'plugins/kinetic.plugin.resize',
		select2             : 'plugins/select2.min',
		datepicker          : 'plugins/bootstrap-datepicker',
		holder              : 'plugins/holder',
		panzer              : 'plugins/panzer',
		panzerlist          : 'plugins/panzerlist',
		timerplugin         : 'plugins/jquery.countdown_plugin.min',
		countdowntimer      : 'plugins/jquery.countdown.min',
		bootbox             : 'plugins/bootbox.min',
		jquery_listnav      : 'plugins/jquery-listnav',
		screwbuttons: 'plugins/jquery.screwdefaultbuttonsV2',
		checkbox: 'plugins/flatui-checkbox',
		unserialize         : 'plugins/unserialize',
		serialize           : 'plugins/serialize',
		fastclick           : 'plugins/fastclick',
		jPages              : 'plugins/jPages.min',
		walnutGlobal        : 'plugins/walnutapp-global'
	},
	shim: {
		underscore: {
			exports: '_'
		},
		jquery: ['underscore'],
		jqueryui: ['jquery'],
		bootstrap: ['jquery'],
		backbone: {
			deps: ['jquery', 'underscore'],
			exports: 'Backbone'
		},
		marionette: {
			deps: ['backbone'],
			exports: 'Marionette'
		},
		tablesorter: ['jquery'],
		tablesorter_pager: ['jquery', 'tablesorter'],
		sidr: ['jquery'],
		unveil: ['jquery'],
		slimroll: ['jquery'],
		core: ['sidr', 'jquery'],
		breakpoints: ['jquery'],
		jqueryvalidate: ['jquery'],
		syphon: ['backbone'],
		underscorestring: ['underscore'],
		mixitup: ['jquery'],
		moment: ['jquery'],
		mmenu: ['jquery'],
		select2: ['jquery', 'bootstrap'],
		datepicker: ['jquery', 'bootstrap'],
		jquerytimer: ['jquery'],
		jquery_listnav: ['jquery'],
		screwbuttons: ['jquery'],
		checkbox: ['bootstrap'],
		panzer: ['jquery'],
		panzerlist : ['jquery'],
		timerplugin: ['jquery'],
		countdowntimer: ['jquery','timerplugin'],
		bootbox : ['jquery','bootstrap'],
		jPages          : ['jquery'],
		app: ['plugins/cordova-pluginloader', 'config/walnut-configloader']
	}
})