({
	baseUrl: './js',
	name: 'plugins/almond',
	include: 'cordova-main',
	// optimize: 'none',
	wrap: false,
	out: '../production/cordova-main.js',
	paths: {
		jquery: 'plugins/jquery',
		jqueryui: 'plugins/jquery.ui',
		bootstrap: 'plugins/bootstrap.min',
		jqueryvalidate: 'plugins/jquery.validate.min',
		underscore: 'plugins/underscore',
		underscorestring: 'plugins/underscorestring',
		backbone: 'plugins/backbone',
		marionette: 'plugins/backbone.marionette',
		text: 'plugins/text',
		app: 'walnut-app',
		syphon: 'plugins/backbone.syphon',
		sidr: 'plugins/jquery.sidr.min',
		slimroll: 'plugins/jquery.slimscroll.min',
		breakpoints: 'plugins/breakpoints',
		mustache: 'plugins/mustache',
		mixitup: 'plugins/jquery.mixitup.min',
		spin: 'plugins/spin',
		jqueryspin: 'plugins/jquery.spin',
		componentloader: 'components/component-loader',
		unveil: 'plugins/jquery.unveil.min',
		detect: 'plugins/detect',
		tablesorter: 'plugins/jquery.tablesorter',
		tablesorter_pager: 'plugins/jquery.tablesorter.pager',
		moment: 'plugins/moment.min',
		select2             : 'plugins/select2.min',
		datepicker          : 'plugins/bootstrap-datepicker',
		timepicker          : 'plugins/bootstrap-timepicker.min',
		jquery_listnav      : 'plugins/jquery-listnav',
		bridget             : 'plugins/jquery.bridget',
		mmenu               : 'plugins/jquery.mmenu.min.all',
		checkbox			: 'plugins/flatui-checkbox',
		holder				: 'plugins/holder',
		videojs				: 'plugins/video',
		videojsplaylist     : 'plugins/videojs-playlists.min',
		panzer              : 'plugins/panzer',
		panzerlist          : 'plugins/panzerlist',
		timerplugin         : 'plugins/jquery.countdown_plugin.min',
		countdowntimer      : 'plugins/jquery.countdown.min',
		spinedit            : 'plugins/bootstrap-spinedit',
		unserialize         : 'plugins/unserialize',
		serialize           : 'plugins/serialize',
		csvparse            : 'plugins/jquery.parse',
		json2csvparse       : 'plugins/json2csv',
		jszip               : 'plugins/jszip',
		fastclick           : 'plugins/fastclick',
		walnutGlobal        : 'plugins/walnutapp-global'
	},
	shim: {
		underscore: {
			exports: '_'
		},
		jquery: ['underscore'],
		jqueryui: ['jquery'],
		bootstrap: ['jquery'],
		backbone: {
			deps: ['jquery', 'underscore'],
			exports: 'Backbone'
		},
		marionette: {
			deps: ['backbone'],
			exports: 'Marionette'
		},
		tablesorter: ['jquery'],
		tablesorter_pager: ['jquery', 'tablesorter'],
		sidr: ['jquery'],
		unveil: ['jquery'],
		slimroll: ['jquery'],
		breakpoints: ['jquery'],
		jqueryvalidate: ['jquery'],
		syphon: ['backbone'],
		underscorestring: ['underscore'],
		mixitup: ['jquery'],
		moment: ['jquery'],
		mmenu: ['jquery'],
		select2: ['jquery', 'bootstrap'],
		datepicker: ['jquery', 'bootstrap'],
		timepicker: ['jquery', 'bootstrap'],
		jquerytimer: ['jquery'],
		jquery_listnav: ['jquery'],
		checkbox  : ['bootstrap'],
		bridget : ['jquery'],
		videojsplaylist : ['videojs'],
		panzer: ['jquery'],
		panzerlist : ['jquery'],
		timerplugin: ['jquery'],
		countdowntimer: ['jquery','timerplugin'],
		spinedit            : ['jquery','bootstrap'],
		csvparse        : ['jquery'],
		json2csvparse   : ['jquery'],
		app: ['plugins/cordova-pluginloader', 'config/walnut-configloader']
	}
})